language: ruby
rvm:
  - 2.7.0

git:
  depth: false

before_script:
- chmod +x ./scripts/cibuild.sh

# Assume bundler is being used, `bundle install` runs by default.
script: ./scripts/cibuild.sh

# Deploy wiki pages and results of build, back to develop branch
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: develop
  keep_history: true
  deployment_file: .versioninfo
  on:
    branch: develop

# Branch whitelist for Travis CI
branches:
  only:
  - develop

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false